//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HH.RMS.WebForm.Register {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenRequest", Namespace="http://schemas.datacontract.org/2004/07/Accentiv.Spark.WebSite.MemberWebsite")]
    [System.SerializableAttribute()]
    public partial class TokenRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RandomStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppID {
            get {
                return this.AppIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AppIDField, value) != true)) {
                    this.AppIDField = value;
                    this.RaisePropertyChanged("AppID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RandomString {
            get {
                return this.RandomStringField;
            }
            set {
                if ((object.ReferenceEquals(this.RandomStringField, value) != true)) {
                    this.RandomStringField = value;
                    this.RaisePropertyChanged("RandomString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityKey {
            get {
                return this.SecurityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityKeyField, value) != true)) {
                    this.SecurityKeyField = value;
                    this.RaisePropertyChanged("SecurityKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenResult", Namespace="http://schemas.datacontract.org/2004/07/Accentiv.Spark.WebSite.MemberWebsite")]
    [System.SerializableAttribute()]
    public partial class TokenResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string randomStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int resultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string randomString {
            get {
                return this.randomStringField;
            }
            set {
                if ((object.ReferenceEquals(this.randomStringField, value) != true)) {
                    this.randomStringField = value;
                    this.RaisePropertyChanged("randomString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                if ((this.resultCodeField.Equals(value) != true)) {
                    this.resultCodeField = value;
                    this.RaisePropertyChanged("resultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultMsg {
            get {
                return this.resultMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.resultMsgField, value) != true)) {
                    this.resultMsgField = value;
                    this.RaisePropertyChanged("resultMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                if ((object.ReferenceEquals(this.signatureField, value) != true)) {
                    this.signatureField = value;
                    this.RaisePropertyChanged("signature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/Accentiv.Spark.WebSite.MemberWebsite")]
    [System.SerializableAttribute()]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RandomStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppID {
            get {
                return this.AppIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AppIDField, value) != true)) {
                    this.AppIDField = value;
                    this.RaisePropertyChanged("AppID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RandomString {
            get {
                return this.RandomStringField;
            }
            set {
                if ((object.ReferenceEquals(this.RandomStringField, value) != true)) {
                    this.RandomStringField = value;
                    this.RaisePropertyChanged("RandomString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestCode {
            get {
                return this.RequestCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestCodeField, value) != true)) {
                    this.RequestCodeField = value;
                    this.RaisePropertyChanged("RequestCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityKey {
            get {
                return this.SecurityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityKeyField, value) != true)) {
                    this.SecurityKeyField = value;
                    this.RaisePropertyChanged("SecurityKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/Accentiv.Spark.WebSite.MemberWebsite")]
    [System.SerializableAttribute()]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string randomStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HH.RMS.WebForm.Register.Member resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int resultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string randomString {
            get {
                return this.randomStringField;
            }
            set {
                if ((object.ReferenceEquals(this.randomStringField, value) != true)) {
                    this.randomStringField = value;
                    this.RaisePropertyChanged("randomString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HH.RMS.WebForm.Register.Member result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                if ((this.resultCodeField.Equals(value) != true)) {
                    this.resultCodeField = value;
                    this.RaisePropertyChanged("resultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultMsg {
            get {
                return this.resultMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.resultMsgField, value) != true)) {
                    this.resultMsgField = value;
                    this.RaisePropertyChanged("resultMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                if ((object.ReferenceEquals(this.signatureField, value) != true)) {
                    this.signatureField = value;
                    this.RaisePropertyChanged("signature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Member", Namespace="http://schemas.datacontract.org/2004/07/Accentiv.Spark.FidesProject.Service.Model" +
        "")]
    [System.SerializableAttribute()]
    public partial class Member : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string birthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string groupidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string headimgurlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string languageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string memberCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string memberProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string membernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string openidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string provinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subscribeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subscribe_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unionidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string birthday {
            get {
                return this.birthdayField;
            }
            set {
                if ((object.ReferenceEquals(this.birthdayField, value) != true)) {
                    this.birthdayField = value;
                    this.RaisePropertyChanged("birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string country {
            get {
                return this.countryField;
            }
            set {
                if ((object.ReferenceEquals(this.countryField, value) != true)) {
                    this.countryField = value;
                    this.RaisePropertyChanged("country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string groupid {
            get {
                return this.groupidField;
            }
            set {
                if ((object.ReferenceEquals(this.groupidField, value) != true)) {
                    this.groupidField = value;
                    this.RaisePropertyChanged("groupid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string headimgurl {
            get {
                return this.headimgurlField;
            }
            set {
                if ((object.ReferenceEquals(this.headimgurlField, value) != true)) {
                    this.headimgurlField = value;
                    this.RaisePropertyChanged("headimgurl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string language {
            get {
                return this.languageField;
            }
            set {
                if ((object.ReferenceEquals(this.languageField, value) != true)) {
                    this.languageField = value;
                    this.RaisePropertyChanged("language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string memberCity {
            get {
                return this.memberCityField;
            }
            set {
                if ((object.ReferenceEquals(this.memberCityField, value) != true)) {
                    this.memberCityField = value;
                    this.RaisePropertyChanged("memberCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string memberProvince {
            get {
                return this.memberProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.memberProvinceField, value) != true)) {
                    this.memberProvinceField = value;
                    this.RaisePropertyChanged("memberProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string membername {
            get {
                return this.membernameField;
            }
            set {
                if ((object.ReferenceEquals(this.membernameField, value) != true)) {
                    this.membernameField = value;
                    this.RaisePropertyChanged("membername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nickname {
            get {
                return this.nicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.nicknameField, value) != true)) {
                    this.nicknameField = value;
                    this.RaisePropertyChanged("nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string openid {
            get {
                return this.openidField;
            }
            set {
                if ((object.ReferenceEquals(this.openidField, value) != true)) {
                    this.openidField = value;
                    this.RaisePropertyChanged("openid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string province {
            get {
                return this.provinceField;
            }
            set {
                if ((object.ReferenceEquals(this.provinceField, value) != true)) {
                    this.provinceField = value;
                    this.RaisePropertyChanged("province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                if ((object.ReferenceEquals(this.remarkField, value) != true)) {
                    this.remarkField = value;
                    this.RaisePropertyChanged("remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sex {
            get {
                return this.sexField;
            }
            set {
                if ((object.ReferenceEquals(this.sexField, value) != true)) {
                    this.sexField = value;
                    this.RaisePropertyChanged("sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subscribe {
            get {
                return this.subscribeField;
            }
            set {
                if ((object.ReferenceEquals(this.subscribeField, value) != true)) {
                    this.subscribeField = value;
                    this.RaisePropertyChanged("subscribe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subscribe_time {
            get {
                return this.subscribe_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.subscribe_timeField, value) != true)) {
                    this.subscribe_timeField = value;
                    this.RaisePropertyChanged("subscribe_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unionid {
            get {
                return this.unionidField;
            }
            set {
                if ((object.ReferenceEquals(this.unionidField, value) != true)) {
                    this.unionidField = value;
                    this.RaisePropertyChanged("unionid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestByOpenId", Namespace="http://schemas.datacontract.org/2004/07/Accentiv.Spark.WebSite.MemberWebsite")]
    [System.SerializableAttribute()]
    public partial class RequestByOpenId : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpenIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RandomStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppID {
            get {
                return this.AppIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AppIDField, value) != true)) {
                    this.AppIDField = value;
                    this.RaisePropertyChanged("AppID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OpenID {
            get {
                return this.OpenIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OpenIDField, value) != true)) {
                    this.OpenIDField = value;
                    this.RaisePropertyChanged("OpenID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RandomString {
            get {
                return this.RandomStringField;
            }
            set {
                if ((object.ReferenceEquals(this.RandomStringField, value) != true)) {
                    this.RandomStringField = value;
                    this.RaisePropertyChanged("RandomString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestCode {
            get {
                return this.RequestCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestCodeField, value) != true)) {
                    this.RequestCodeField = value;
                    this.RaisePropertyChanged("RequestCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityKey {
            get {
                return this.SecurityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityKeyField, value) != true)) {
                    this.SecurityKeyField = value;
                    this.RaisePropertyChanged("SecurityKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterRequest", Namespace="http://schemas.datacontract.org/2004/07/Accentiv.Spark.WebSite.MemberWebsite")]
    [System.SerializableAttribute()]
    public partial class RegisterRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RandomStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HH.RMS.WebForm.Register.RegisterUserInfoModel UserInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppID {
            get {
                return this.AppIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AppIDField, value) != true)) {
                    this.AppIDField = value;
                    this.RaisePropertyChanged("AppID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RandomString {
            get {
                return this.RandomStringField;
            }
            set {
                if ((object.ReferenceEquals(this.RandomStringField, value) != true)) {
                    this.RandomStringField = value;
                    this.RaisePropertyChanged("RandomString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityKey {
            get {
                return this.SecurityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityKeyField, value) != true)) {
                    this.SecurityKeyField = value;
                    this.RaisePropertyChanged("SecurityKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HH.RMS.WebForm.Register.RegisterUserInfoModel UserInfo {
            get {
                return this.UserInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.UserInfoField, value) != true)) {
                    this.UserInfoField = value;
                    this.RaisePropertyChanged("UserInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterUserInfoModel", Namespace="http://schemas.datacontract.org/2004/07/Accentiv.Spark.WebSite.MemberWebsite.Mode" +
        "ls")]
    [System.SerializableAttribute()]
    public partial class RegisterUserInfoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int birthDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int birthMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int birthYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int channelCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long cityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string openIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long provinceIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int birthDay {
            get {
                return this.birthDayField;
            }
            set {
                if ((this.birthDayField.Equals(value) != true)) {
                    this.birthDayField = value;
                    this.RaisePropertyChanged("birthDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int birthMonth {
            get {
                return this.birthMonthField;
            }
            set {
                if ((this.birthMonthField.Equals(value) != true)) {
                    this.birthMonthField = value;
                    this.RaisePropertyChanged("birthMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int birthYear {
            get {
                return this.birthYearField;
            }
            set {
                if ((this.birthYearField.Equals(value) != true)) {
                    this.birthYearField = value;
                    this.RaisePropertyChanged("birthYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int channelCode {
            get {
                return this.channelCodeField;
            }
            set {
                if ((this.channelCodeField.Equals(value) != true)) {
                    this.channelCodeField = value;
                    this.RaisePropertyChanged("channelCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long cityId {
            get {
                return this.cityIdField;
            }
            set {
                if ((this.cityIdField.Equals(value) != true)) {
                    this.cityIdField = value;
                    this.RaisePropertyChanged("cityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gender {
            get {
                return this.genderField;
            }
            set {
                if ((this.genderField.Equals(value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                if ((object.ReferenceEquals(this.mobileField, value) != true)) {
                    this.mobileField = value;
                    this.RaisePropertyChanged("mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string openId {
            get {
                return this.openIdField;
            }
            set {
                if ((object.ReferenceEquals(this.openIdField, value) != true)) {
                    this.openIdField = value;
                    this.RaisePropertyChanged("openId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long provinceId {
            get {
                return this.provinceIdField;
            }
            set {
                if ((this.provinceIdField.Equals(value) != true)) {
                    this.provinceIdField = value;
                    this.RaisePropertyChanged("provinceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterResult", Namespace="http://schemas.datacontract.org/2004/07/Accentiv.Spark.WebSite.MemberWebsite")]
    [System.SerializableAttribute()]
    public partial class RegisterResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string randomStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int resultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string randomString {
            get {
                return this.randomStringField;
            }
            set {
                if ((object.ReferenceEquals(this.randomStringField, value) != true)) {
                    this.randomStringField = value;
                    this.RaisePropertyChanged("randomString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                if ((this.resultCodeField.Equals(value) != true)) {
                    this.resultCodeField = value;
                    this.RaisePropertyChanged("resultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultMsg {
            get {
                return this.resultMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.resultMsgField, value) != true)) {
                    this.resultMsgField = value;
                    this.RaisePropertyChanged("resultMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                if ((object.ReferenceEquals(this.signatureField, value) != true)) {
                    this.signatureField = value;
                    this.RaisePropertyChanged("signature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Register.IWebservice_Occitane")]
    public interface IWebservice_Occitane {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Occitane/GetAccessTokenService", ReplyAction="http://tempuri.org/IWebservice_Occitane/GetAccessTokenServiceResponse")]
        HH.RMS.WebForm.Register.TokenResult GetAccessTokenService(HH.RMS.WebForm.Register.TokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Occitane/GetAccessTokenService", ReplyAction="http://tempuri.org/IWebservice_Occitane/GetAccessTokenServiceResponse")]
        System.Threading.Tasks.Task<HH.RMS.WebForm.Register.TokenResult> GetAccessTokenServiceAsync(HH.RMS.WebForm.Register.TokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Occitane/GetMemberInfo", ReplyAction="http://tempuri.org/IWebservice_Occitane/GetMemberInfoResponse")]
        HH.RMS.WebForm.Register.Result GetMemberInfo(HH.RMS.WebForm.Register.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Occitane/GetMemberInfo", ReplyAction="http://tempuri.org/IWebservice_Occitane/GetMemberInfoResponse")]
        System.Threading.Tasks.Task<HH.RMS.WebForm.Register.Result> GetMemberInfoAsync(HH.RMS.WebForm.Register.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Occitane/GetMemberInfoByOpenId", ReplyAction="http://tempuri.org/IWebservice_Occitane/GetMemberInfoByOpenIdResponse")]
        HH.RMS.WebForm.Register.Result GetMemberInfoByOpenId(HH.RMS.WebForm.Register.RequestByOpenId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Occitane/GetMemberInfoByOpenId", ReplyAction="http://tempuri.org/IWebservice_Occitane/GetMemberInfoByOpenIdResponse")]
        System.Threading.Tasks.Task<HH.RMS.WebForm.Register.Result> GetMemberInfoByOpenIdAsync(HH.RMS.WebForm.Register.RequestByOpenId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Occitane/RegisterService", ReplyAction="http://tempuri.org/IWebservice_Occitane/RegisterServiceResponse")]
        HH.RMS.WebForm.Register.RegisterResult RegisterService(HH.RMS.WebForm.Register.RegisterRequest registerRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Occitane/RegisterService", ReplyAction="http://tempuri.org/IWebservice_Occitane/RegisterServiceResponse")]
        System.Threading.Tasks.Task<HH.RMS.WebForm.Register.RegisterResult> RegisterServiceAsync(HH.RMS.WebForm.Register.RegisterRequest registerRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebservice_OccitaneChannel : HH.RMS.WebForm.Register.IWebservice_Occitane, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Webservice_OccitaneClient : System.ServiceModel.ClientBase<HH.RMS.WebForm.Register.IWebservice_Occitane>, HH.RMS.WebForm.Register.IWebservice_Occitane {
        
        public Webservice_OccitaneClient() {
        }
        
        public Webservice_OccitaneClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Webservice_OccitaneClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Webservice_OccitaneClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Webservice_OccitaneClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HH.RMS.WebForm.Register.TokenResult GetAccessTokenService(HH.RMS.WebForm.Register.TokenRequest request) {
            return base.Channel.GetAccessTokenService(request);
        }
        
        public System.Threading.Tasks.Task<HH.RMS.WebForm.Register.TokenResult> GetAccessTokenServiceAsync(HH.RMS.WebForm.Register.TokenRequest request) {
            return base.Channel.GetAccessTokenServiceAsync(request);
        }
        
        public HH.RMS.WebForm.Register.Result GetMemberInfo(HH.RMS.WebForm.Register.Request request) {
            return base.Channel.GetMemberInfo(request);
        }
        
        public System.Threading.Tasks.Task<HH.RMS.WebForm.Register.Result> GetMemberInfoAsync(HH.RMS.WebForm.Register.Request request) {
            return base.Channel.GetMemberInfoAsync(request);
        }
        
        public HH.RMS.WebForm.Register.Result GetMemberInfoByOpenId(HH.RMS.WebForm.Register.RequestByOpenId request) {
            return base.Channel.GetMemberInfoByOpenId(request);
        }
        
        public System.Threading.Tasks.Task<HH.RMS.WebForm.Register.Result> GetMemberInfoByOpenIdAsync(HH.RMS.WebForm.Register.RequestByOpenId request) {
            return base.Channel.GetMemberInfoByOpenIdAsync(request);
        }
        
        public HH.RMS.WebForm.Register.RegisterResult RegisterService(HH.RMS.WebForm.Register.RegisterRequest registerRequest) {
            return base.Channel.RegisterService(registerRequest);
        }
        
        public System.Threading.Tasks.Task<HH.RMS.WebForm.Register.RegisterResult> RegisterServiceAsync(HH.RMS.WebForm.Register.RegisterRequest registerRequest) {
            return base.Channel.RegisterServiceAsync(registerRequest);
        }
    }
}
